version: '3'
services:
  db:
    container_name: db_demo
    image: docker.kilid.org/postgis/postgis:15-3.3
    volumes:
      - postgres-local-db1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_db_user
      POSTGRES_PASSWORD: app_pwd
      POSTGRES_DB: app_db
    ports:
      - 5420:5432

volumes:
  postgres-local-db1: