
spring:
    datasource:
        url: jdbc:postgresql://localhost:5420/app_db?createDatabaseIfNotExist=true
        username: app_db_user
        password: app_pwd
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

application:
    security:
        secret_key: ${SECRET_KEY:Vdj@scoinwerujv$zniwndubicnoew-sc$dcknkewue}
        token_expiration_days: 1

